# Generated by Django 4.1.3 on 2022-11-29 11:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pesel', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('street', models.CharField(max_length=128)),
                ('build_number', models.CharField(max_length=16)),
                ('apartment_number', models.CharField(max_length=16, null=True)),
                ('post_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=128)),
                ('build_number', models.CharField(max_length=16)),
                ('apartment_number', models.CharField(max_length=16, null=True)),
                ('post_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TestResultPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_test', models.CharField(choices=[(1, 'Badanie krwi'), (2, 'Badanie moczu')], max_length=128)),
                ('date_test', models.DateField()),
                ('leukocytes', models.FloatField(null=True)),
                ('erythrocytes', models.FloatField(null=True)),
                ('hemoglobin', models.FloatField(null=True)),
                ('hematocrit', models.IntegerField(null=True)),
                ('mcv', models.IntegerField(null=True)),
                ('mch', models.IntegerField(null=True)),
                ('mchc', models.IntegerField(null=True)),
                ('thrombocytes', models.IntegerField(null=True)),
                ('rdw', models.FloatField(null=True)),
                ('pdw', models.IntegerField(null=True)),
                ('plcr', models.IntegerField(null=True)),
                ('neutrophils', models.IntegerField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacjent.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacjent.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacjent.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_employment', models.DateField(default=datetime.date)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacjent.doctor')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacjent.place')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='special',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pacjent.special'),
        ),
    ]
