# Generated by Django 4.1.4 on 2023-01-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacjent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresultpatient',
            name='bacteria',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='bilirubin',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='color',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='epithelial_rollers',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='erythrocytes_casts',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='flat_epithelium',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='glassy_rods',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='glucose',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='grain_rolls',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='ketone_bodies',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='leukocyte_casts',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='look',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='nitrites',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='oxalates',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='ph',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='phosphates',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='protein',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='round_epithelium',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='smell',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='soaked',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='specific_gravity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='urobilinogen',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testresultpatient',
            name='yeast',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='testresultpatient',
            name='name_test',
            field=models.CharField(choices=[(1, 'Badanie krwi'), (2, 'Badanie moczu'), (3, 'Morfologia'), (4, 'Glukoza'), (5, 'Próby wątrobowe'), (5, 'Badanie kreatyny')], max_length=128),
        ),
    ]
